### PR TITLE
Better support for text nodes

### PR DESCRIPTION
**Pull request by polotek**
This is branch to add better support for adding text nodes per #263. The task list below outlines the steps needed for completion.

- [x] add `addText` method to append text nodes to an element.
- [x] add `addPrevText` and `addNextText`

### CODE REVIEW

**Comment by defunctzombie** [comment]
:+1:

**Comment by polotek** [comment]
@defunctzombie how come we never landed this? I'm looking back and don't really see a reason. I think it's just that I never did it. Now it has conflicts. I'll fix them later this week and land this.

**Comment by defunctzombie** [comment]
@polotek dunno, I gave the thumbs up but probably thought you would merge it.

**Comment by defunctzombie** [comment]
Closing. I think another issue resolved most of the items here. If others want to raise any more issues we can handle those separately.

**Pull request closed without merging**
