### PR TITLE
Remove previous children when setting element text

### PR DESCRIPTION
**Pull request by teleological**
* Previous children are freed when text is set

### CODE REVIEW

**Comment by rc0x03** [comment]
:+1: looks good as long as it works for child attributes and namespaces as well.

**Comment by teleological** [comment]
@rc0x03 Since attributes and namespaces don't descent from XmlElement, this won't affect how they are handled. But as far as I can tell, no special handling is needed. Do you have a case in mind?

**Comment by rc0x03** [comment]
Any child attributes, namespaces, text nodes and comment nodes should also cause a segfault when their parent node text is modified and they try to unref their parent. Look at the attribute example in the test code I provided.

**Comment by rc0x03** [comment]
Actually, since we're unlinking the child it shouldn't matter because we ref the child before we can ref its attributes or namespaces.

**Pull request merged**
