### PR TITLE
Return value for [namespace(ns)] changed to [node].

### PR DESCRIPTION
**Pull request by bhamon**
Proposal to close the issue #356.

### CODE REVIEW

**Comment by rc0x03** [comment]
:+1:

**Comment by rc0x03** [comment]
Squash the commits and this should be good to merge as long as @defunctzombie approves.

**Comment by rc0x03** [comment]
@bhamon just squash the commits and we can merge this

**Comment by bhamon** [comment]
Sorry for the delay, now it's done.

**Pull request merged**
