### PR TITLE
Added preprocessor conditions to config.h to build on windows platforms.

### PR DESCRIPTION
**Pull request by ashkandaie**
In regard to #381. Here is a PR that fixes the build on windows platforms.

### CODE REVIEW

**Comment by ashkandaie** [comment]
Forgot to mention that the parse test in xml_parser fails the last assertion of assert.equal(str, doc.toString());

**Comment by defunctzombie** [comment]
Great!

I am wondering tho how this ever compiled on windows. Looking at the file blame information, it seems that the code in question was the same before and after the recent update of libxml2.

**Comment by ashkandaie** [comment]
Interesting. I'll take a look when time permits.

**Comment by gagern** [comment]
> I am wondering tho how this ever compiled on windows. Looking at the file blame information, it seems that the code in question was the same before and after the recent update of libxml2.

There were some `#undef` lines in `vendor/libxml/libxml.h` which [the update removed](https://github.com/polotek/libxmljs/commit/9acfcaf7d736ec64656bce04259e3b526ecc4b5d#diff-249d2ce676689422cc0e3f3b3c87deac). Something I adressed in https://github.com/gagern/libxmljs/commit/5c328891854ed23ae3c8abcb0f0c3ccfb86d7d3e for #297 which you rejected.

**Pull request merged**
