### PR TITLE
Expose text node class

### PR DESCRIPTION
**Pull request by davydog187**
Taking a look at #265, it seemed that there could be better support for Text nodes by exposing a `Text` class. This PR does just that.

I will continue to improve the test coverage and review the features exposed. This PR is to get the discussion started

### CODE REVIEW

**Comment by stsvilik** [comment]
So implementation signature suggests we can do something like this?

```js
var newTextNode = new libxml.Text(document, "my text");
```
Where we can later append new text node to another node

```js
var newTextNode = new libxml.Text(document, "my text");
var newElement = new libxml.Element("div");
newElement.addChild(newTextNode);
```
and in relation to #265 we could also do
```js
var newTextNode = new libxml.Text(document, "my text");
var newElement = new libxml.Element("div");

//To let text follow the tag ex.: <div></div>my text
newElement.addPrevSibling(newTextNode);
//or to let text precede tag ex.: my text<div></div>
newElement.addNextSibling(newTextNode);
```
Is this correct?

**Comment by davydog187** [comment]
Added a test to prove your first test case works.

**Comment by davydog187** [comment]
What does @polotek think?

**Comment by davydog187** [comment]
Also validated your second question.

**Comment by davydog187** [comment]
This should also address #263

**Comment by rc0x03** [comment]
Why not inherit from `XmlElement` instead of implementing most of its functions separately? This seems like it could cause consistency issues in the future. It would also significantly reduce the size of the code.

**Comment by rc0x03** [comment]
Also, if it does inherit from `XmlElement` then we need to decide what inapplicable things like `node->name()` should do. They could be removed and unimplimented. They could throw an error if it's a text node. They could do nothing or return an empty string. They could do what their DOM equivalents would do, for example `text_node.nodeName` in a browser would be `"#text"`. Maybe @polotek or  @teleological can offer suggestions for that.

**Comment by rc0x03** [comment]
Actually, since a libxml text node is the same thing as a regular node then `XmlElement` might be able to handle inapplicable functions like `node->attrs()` automatically without causing issues.

**Comment by stsvilik** [comment]
IMHO the difference between XmlNode and XmlElement is significant and most of the exposed methods do not apply to Text, for starters you can not append anything to a text, Text has no attributes nor does it need a name method. Most of the extra weight which comes with XmlElement is extraneous.

**Comment by rc0x03** [comment]
@stsvilik great points. I just wish the shared functions were all in one location. Especially since garbage collection reference counting might be added to functions like `remove` and `replace` in the future.

Also, you may need to add a `node->type == "text"` case inside `XmlNode::New`

**Comment by davydog187** [comment]
@rc0x03 I'd be happy to work towards removing duplicate logic. If this was javascript I'd share them by way of a mixin. In C++, there are also facilities to provide mixins but I'm not sure how well they would play with `NAN`. Any suggestions?

**Comment by davydog187** [comment]
@rc0x03 also the node type is not necessary. If you take a look at my tests you'll see that its already been validated.

Possibly one way to share some of this functionality is to move some of the duplicated code up into XmlNode? I haven't validated this would work yet, but it could be an option

**Comment by stsvilik** [comment]
I kinda need this feature - is anything besides a hypothetical refactoring of shared traits preventing this feature from going in? I feel that refactoring could wait while this feature might as well be used now.

**Comment by rc0x03** [comment]
@stsvilik I agree, this can be merged as-is for now

**Comment by stsvilik** [comment]
:+1:  lets do it :)

**Comment by stsvilik** [comment]
Please create new release with these changes

**Comment by defunctzombie** [comment]
@stsvilik I am waiting on two more PRs to finalize then a release. If you really need a feature you can depend directly on a github repo from npm.

**Pull request merged**
